import { compactText, normalizeDate, normalizeInteger, normalizeMoney } from '../helpers.js';
function clean(value){return String(value??'').replace(/\s+/g,' ').trim();}
function linesOf(text){return String(text||'').replace(/\u00a0/g,' ').split(/\r?\n/).map((line)=>line.replace(/\s+$/g,''));}
function parseShipTo(rawLines){const index=rawLines.findIndex((line)=>/Seller\/Supplier Info/i.test(line)&&/Ship To:/i.test(line));if(index<0)return null;const right=rawLines.slice(index+1,index+6).map((line)=>{const pieces=String(line||'').split(/\s{8,}/).map(clean).filter(Boolean);return pieces.length>=2?pieces[pieces.length-1]:null;}).filter(Boolean);const cityLine=right.find((v)=>/\b[A-Z]{2}\s+\d{5}/i.test(v))||null;const m=cityLine?.match(/^(.+?)\s+([A-Z]{2})\s+(\d{5}(?:-\d{4})?)$/i);return{semantics:'SHIP_TO',name_raw:right[0]||null,facility_raw:right.find((v,i)=>i>0&&!/^\d+\s+/.test(v)&&v!==cityLine)||null,address1_raw:right.find((v)=>/^\d+\s+/.test(v))||null,city_raw:clean(m?.[1])||null,state_raw:clean(m?.[2]).toUpperCase()||null,postal_raw:clean(m?.[3])||null,block_raw:right};}
function upperUom(value){return clean(value).toUpperCase();}
export function parseColony({text}){const rawLines=linesOf(text);const oneLine=compactText(text);const legalEntityRaw=clean(oneLine.match(/\b(COLONY BRANDS, INC)\b/i)?.[1])||null;const orderNo=clean(oneLine.match(/\bPO Number\s+([A-Z0-9-]+)/i)?.[1])||null;const orderDateRaw=clean(oneLine.match(/\bPO Date\s+(\d{1,2}\/\d{1,2}\/\d{2,4})/i)?.[1])||null;const termsRaw=clean(oneLine.match(/\bTerms of Sale\s+Freight Terms\s+Ship Via\s+(.+?)\s+(FREIGHT\s+(?:COLLECT|PREPAID))\s+(.+?)\s+CORRECT PO RELEASE/i)?.[1])||null;const freightRaw=clean(oneLine.match(/\b(FREIGHT\s+(?:COLLECT|PREPAID))\b/i)?.[1])||null;const shipViaRaw=clean(oneLine.match(/\b(?:FREIGHT\s+(?:COLLECT|PREPAID))\s+(CONTACT\s+SC\s+TRAFFIC)\b/i)?.[1])||null;const shipTo=parseShipTo(rawLines);
  const itemHeaderIndex=rawLines.findIndex((line)=>/PLN\s*#\s*\/\s*Item\s*#/i.test(line));const rel=itemHeaderIndex>=0?rawLines.slice(itemHeaderIndex+1).findIndex((line)=>/^\s*[A-Z0-9]+\s*\/\s*[A-Z0-9]+\s+#[A-Z0-9-]+\s+.+/i.test(line)):-1;const itemIndex=rel>=0?itemHeaderIndex+1+rel:-1;const itemLine=itemIndex>=0?rawLines[itemIndex]:'';const itemMatch=itemLine.match(/^\s*([A-Z0-9]+)\s*\/\s*([A-Z0-9]+)\s+#?([A-Z0-9-]+)\s+(.+?)\/([A-Z][A-Z /.-]+)\s*$/i);const releaseLine=itemIndex>=0?rawLines.slice(itemIndex+1,itemIndex+8).find((line)=>/^\s*\d{5}\s+NEW\s+/i.test(line))||'':'';const releaseMatch=releaseLine.match(/^\s*(\d{5})\s+(\S+)\s+([\d,]+)\s+([\d,]+)\s+(\d{1,2}\/\d{1,2}\/\d{4})\s+([\d,.]+)\s+([A-Z]+)\s+\$([\d,]+(?:\.\d{2})?)\s*$/i);
  const plnRaw=clean(itemMatch?.[1])||null,itemNumberRaw=clean(itemMatch?.[2])||null,styleRaw=clean(itemMatch?.[3])||null,descriptionRaw=clean(itemMatch?.[4])||null,colorRaw=clean(itemMatch?.[5])||null;const releaseQtyRaw=normalizeInteger(releaseMatch?.[3]),balanceDueRaw=normalizeInteger(releaseMatch?.[4]),dueDateRaw=clean(releaseMatch?.[5])||null,unitPriceRaw=normalizeMoney(releaseMatch?.[6]),uomRaw=clean(releaseMatch?.[7])||null,extPriceRaw=normalizeMoney(releaseMatch?.[8]);
  const line=styleRaw?{line_no:1,customer_sku:itemNumberRaw,ticket_sku:null,upc:null,style_raw:styleRaw,style_code:null,color_raw:colorRaw,color_code:null,size_raw:null,size_code:null,description:descriptionRaw,sales_price:unitPriceRaw,list_price:null,qty_total:releaseQtyRaw,warehouse_code:null,raw:{source:'colony_purchase_order_v1',pln_number_raw:plnRaw,item_number_raw:itemNumberRaw,printed_style_marker_raw:styleRaw,style_resolution_hint:'EXACT_MASTER_STYLE_NORMALIZED',description_raw:descriptionRaw,color_raw:colorRaw,release_number_raw:clean(releaseMatch?.[1])||null,release_status_raw:clean(releaseMatch?.[2])||null,release_qty_raw:releaseQtyRaw,balance_due_raw:balanceDueRaw,in_house_due_date_raw:dueDateRaw,unit_price_raw:unitPriceRaw,quantity_uom_raw:uomRaw,quantity_semantics:upperUom(uomRaw)==='EA'?'EACH':'UNSPECIFIED_COUNT',extended_price_raw:extPriceRaw}}:null;
  const conflicts=[];if(line&&line.qty_total!==null&&line.sales_price!==null&&extPriceRaw!==null){const calc=Number(line.qty_total)*Number(line.sales_price);if(Number.isFinite(calc)&&Math.abs(extPriceRaw-calc)>0.01)conflicts.push({field:'totals.amount',code:'printed_total_mismatch',severity:'high',blocking:true,message:'Printed extended price does not match release quantity x unit price.',printed:extPriceRaw,extracted:calc});}
  const warnings=[];if(/TRAFFIC#COLONYBRANDS\.COM/i.test(text)&&/TRAFFIC@COLONYBRANDS\.COM/i.test(text))warnings.push({field:'document_contact',code:'source_email_typo',severity:'low',message:'Document contains TRAFFIC#COLONYBRANDS.COM and later TRAFFIC@COLONYBRANDS.COM; the first appears to be a source-document typo. No Sales Order field is derived from it.'});
  return{parser:'colony',document_family:'colony_purchase_order',layout_version:'colony_purchase_order_v1',document_identity:{legal_entity_raw:legalEntityRaw,brand_raw:clean(oneLine.match(/\b(COLONY BRANDS)\b/i)?.[1])||null,customer_candidate:'COLONY',customer_candidate_source:'document_family',a2000_customer_code:null},confidence:orderNo&&line?0.98:line?0.8:0.4,header:{customer_raw:legalEntityRaw,customer_code:null,order_no:orderNo,order_date:normalizeDate(orderDateRaw),start_date:null,cancel_date:null,book_date:null,dept_raw:null,dept_code:null,division_code:null,store_raw:null,store_code:null,terms_raw:termsRaw,terms_code:null,ship_via_code:null,warehouse_code:null,raw:{order_date_raw:orderDateRaw,terms_raw:termsRaw,freight_raw:freightRaw,ship_via_raw:shipViaRaw,ship_to:shipTo,due_date_raw:dueDateRaw,due_date_semantics:'IN_HOUSE_DUE_NOT_START_OR_CANCEL'}},lines:line?[line]:[],totals:{qty:line?.qty_total??null,amount:extPriceRaw??null},conflicts,warnings};
}
