import { compactText, normalizeDate, normalizeInteger, normalizeMoney } from '../helpers.js';
function clean(value){return String(value??'').replace(/\s+/g,' ').trim();}
function linesOf(text){return String(text||'').replace(/\u00a0/g,' ').split(/\r?\n/).map((line)=>line.replace(/\s+$/g,''));}
function parseShipTo(rawLines){ const index=rawLines.findIndex((line)=>/PLEASE SHIP TO THE BELOW ADDRESS/i.test(line)); if(index<0)return null; const candidates=rawLines.slice(index+1,index+6).map((line)=>clean(String(line||'').split(/\s{8,}/)[0])).filter(Boolean); const cityLine=candidates.find((v)=>/,\s*[A-Z]{2}\s+\d{5}/i.test(v))||null; const m=cityLine?.match(/^(.+?),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?)$/i); return {semantics:'SHIP_TO',name_raw:candidates[0]||null,address1_raw:candidates.find((v)=>/^\d+\s+/.test(v))||null,city_raw:clean(m?.[1])||null,state_raw:clean(m?.[2]).toUpperCase()||null,postal_raw:clean(m?.[3])||null,block_raw:candidates}; }
export function parseMacysBacks({text}){ const rawLines=linesOf(text); const oneLine=compactText(text); const vendorNameRaw=clean(oneLine.match(/\bVENDOR NAME:\s*(.+?)\s+ROUTE\/START SHIP DATE:/i)?.[1])||null; const startDateRaw=clean(oneLine.match(/\bROUTE\/START SHIP DATE:\s*(\d{1,2}\/\d{1,2}\/\d{4})/i)?.[1])||null; const inDcByRaw=clean(oneLine.match(/\bIN MACYS BACKSTAGE DC BY:\s*(\d{1,2}\/\d{1,2}\/\d{4})/i)?.[1])||null; const orderNo=clean(oneLine.match(/\bPO#\s*([A-Z0-9-]+)/i)?.[1])||null; const deptRaw=clean(oneLine.match(/\bDEPT #:\s*([A-Z0-9-]+)/i)?.[1])||null; const vendorNumberRaw=clean(oneLine.match(/\bVendor #:\s*([A-Z0-9-]+)/i)?.[1])||null; const termsRaw=clean(oneLine.match(/\bTerms:\s*([^\s]+(?:\s+\d+)?)/i)?.[1])||null; const preTicketRaw=clean(oneLine.match(/\bPRETICKET:\s*(YES|NO)/i)?.[1])||null; const shipTo=parseShipTo(rawLines);
  const rowPattern=/^\s*(\d+)\s{2,}([A-Z0-9][A-Z0-9./-]+)\s{2,}(.+?)\s{2,}(.+?)\s{2,}\$([\d,.]+)\s{2,}([\d,]+)\s{2,}\$([\d,]+\.\d{2})\s*$/i; const lines=[];
  for(const rawLine of rawLines){const m=rawLine.match(rowPattern); if(!m)continue; const lineNoRaw=normalizeInteger(m[1]); const vendorStyleRaw=clean(m[2]); const vendorDescriptionRaw=clean(m[3]); const nrfColorDescRaw=clean(m[4]); const costRaw=normalizeMoney(m[5]); const totalUnitsRaw=normalizeInteger(m[6]); const extCostRaw=normalizeMoney(m[7]); lines.push({line_no:lineNoRaw,customer_sku:null,ticket_sku:null,upc:null,style_raw:vendorStyleRaw,style_code:null,color_raw:nrfColorDescRaw,color_code:null,size_raw:null,size_code:null,description:vendorDescriptionRaw,sales_price:costRaw,list_price:null,qty_total:totalUnitsRaw,warehouse_code:null,raw:{source:'macys_backstage_po_v1',vendor_style_raw:vendorStyleRaw,style_resolution_hint:'EXACT_MASTER_SKU_NORMALIZED',vendor_description_raw:vendorDescriptionRaw,nrf_color_description_raw:nrfColorDescRaw,cost_raw:costRaw,total_units_raw:totalUnitsRaw,quantity_semantics:'EACH',quantity_uom_raw:'TOTAL UNITS',ext_cost_raw:extCostRaw,matched_text:rawLine.trim()}});}
  const printedQty=normalizeInteger(oneLine.match(/\bTOTAL UNITS\s+([\d,]+)/i)?.[1]); const printedAmount=normalizeMoney(oneLine.match(/\bTOTAL COST\b.*?\bDOLLARS\s+\$([\d,]+(?:\.\d{2})?)/i)?.[1]); const calculatedQty=lines.reduce((s,l)=>s+(Number(l.qty_total)||0),0)||null; const calculatedAmount=lines.reduce((s,l)=>s+(Number(l.raw?.ext_cost_raw)||0),0)||null; const conflicts=[]; if(printedQty!==null&&calculatedQty!==null&&printedQty!==calculatedQty)conflicts.push({field:'totals.qty',code:'printed_total_mismatch',severity:'high',blocking:true,message:'Printed TOTAL UNITS do not match extracted line quantities.',printed:printedQty,extracted:calculatedQty}); if(printedAmount!==null&&calculatedAmount!==null&&Math.abs(printedAmount-calculatedAmount)>0.01)conflicts.push({field:'totals.amount',code:'printed_total_mismatch',severity:'high',blocking:true,message:'Printed TOTAL COST DOLLARS does not match extracted line extensions.',printed:printedAmount,extracted:calculatedAmount});
  return {parser:'macysbacks',document_family:'macys_backstage_purchase_order',layout_version:'macys_backstage_po_v1',document_identity:{legal_entity_raw:clean(oneLine.match(/\b(MACY'?S BACKSTAGE)\b/i)?.[1])||null,brand_raw:clean(oneLine.match(/\b(MACY'?S BACKSTAGE)\b/i)?.[1])||null,customer_candidate:'MACYSBACKS',customer_candidate_source:'document_family',a2000_customer_code:null},confidence:orderNo&&lines.length?0.98:lines.length?0.8:0.4,header:{customer_raw:clean(oneLine.match(/\b(MACY'?S BACKSTAGE)\b/i)?.[1])||null,customer_code:null,order_no:orderNo,order_date:null,start_date:normalizeDate(startDateRaw),cancel_date:normalizeDate(inDcByRaw),book_date:null,dept_raw:deptRaw,dept_code:null,division_code:null,store_raw:null,store_code:null,terms_raw:termsRaw,terms_code:null,ship_via_code:null,warehouse_code:null,raw:{vendor_name_raw:vendorNameRaw,vendor_number_raw:vendorNumberRaw,route_start_ship_date_raw:startDateRaw,in_dc_by_raw:inDcByRaw,cancel_date_source_raw:'IN MACYS BACKSTAGE DC BY',in_dc_by_semantics:'IN_DC_BY_NOT_CANCEL_DATE',dept_raw:deptRaw,terms_raw:termsRaw,preticket_raw:preTicketRaw,ship_to:shipTo}},lines,totals:{qty:calculatedQty,amount:calculatedAmount,printed_qty_raw:printedQty,printed_amount_raw:printedAmount},conflicts};
}
