import { compactText, normalizeDate, normalizeInteger, normalizeMoney } from '../helpers.js';
function clean(value){return String(value??'').replace(/\s+/g,' ').trim();}
function linesOf(text){return String(text||'').replace(/\u00a0/g,' ').split(/\r?\n/).map((line)=>line.replace(/\s+$/g,''));}
function parseShipTo(rawLines){
  const index=rawLines.findIndex((line)=>/Ship To:\s*\d+\s*-\s*ZUMIEZ/i.test(line)); if(index<0)return null;
  const firstLine=rawLines[index]; const firstMatch=firstLine.match(/Ship To:\s*(\d+)\s*-\s*(.+?)\s*$/i);
  const rightColumn=rawLines.slice(index,index+8).map((line,offset)=>{if(offset===0)return clean(firstMatch?.[2])||null; const pieces=String(line||'').split(/\s{8,}/).map(clean).filter(Boolean); return pieces.length>=2?pieces[pieces.length-1]:null;}).filter(Boolean);
  const address1=rightColumn.find((v)=>/^\d+\s+/.test(v)&&!/\bPhone\b/i.test(v))||null;
  const cityStatePostal=rightColumn.find((v)=>/,\s*[A-Z]{2}\s+\d{5}/i.test(v))||null; const m=cityStatePostal?.match(/^(.+?),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?)$/i);
  return { semantics:'SHIP_TO', store_code_raw:clean(firstMatch?.[1])||null, name_raw:clean(firstMatch?.[2])||null, address1_raw:address1, city_raw:clean(m?.[1])||null, state_raw:clean(m?.[2]).toUpperCase()||null, postal_raw:clean(m?.[3])||null, block_raw:rightColumn };
}
function parseDescription(blockLines){
  const start=blockLines.findIndex((line)=>/\bDesc:/i.test(line)); if(start<0)return null; const parts=[];
  for(let i=start;i<blockLines.length;i+=1){ const line=String(blockLines[i]||''); if(i>start&&/\bCOLOR:/i.test(line))break; const left=clean(line.split(/\s{8,}/)[0]); const value=i===start?clean(left.replace(/^.*?Desc:\s*/i,'')):left; if(value&&!/^Qty\.\s+Ext\.\s+Cost$/i.test(value))parts.push(value); }
  return clean(parts.join(' '))||null;
}
export function parseZumiez({text}){
  const rawLines=linesOf(text); const oneLine=compactText(text); const orderNo=clean(oneLine.match(/\bPURCHASE ORDER:\s*([A-Z0-9-]+)/i)?.[1])||null; const shipTo=parseShipTo(rawLines);
  const poDateRaw=clean(oneLine.match(/\bPO Date\s+(\d{1,2}\/\d{1,2}\/\d{2,4})/i)?.[1])||null; const shipDateRaw=clean(oneLine.match(/\bShip Date\s+(\d{1,2}\/\d{1,2}\/\d{2,4})/i)?.[1])||null; const cancelDateRaw=clean(oneLine.match(/\bCancel Date\s+(\d{1,2}\/\d{1,2}\/\d{2,4})/i)?.[1])||null; const termsRaw=clean(oneLine.match(/\bTerms\s+(.+?)\s+Carrier\b/i)?.[1])||null; const buyerRaw=clean(oneLine.match(/\bBuyer\s+(.+?)\s+Ship Date\b/i)?.[1])||null;
  const starts=[]; rawLines.forEach((line,index)=>{if(/^\s*Zumiez #:\s*\d+/i.test(line))starts.push(index);}); const lines=[];
  for(let pos=0;pos<starts.length;pos+=1){ const start=starts[pos]; const end=pos+1<starts.length?starts[pos+1]:rawLines.length; const blockLines=rawLines.slice(start,end); const block=compactText(blockLines.join('\n'));
    const customerSkuRaw=clean(block.match(/Zumiez #:\s*(\d+)/i)?.[1])||null; const deptClassRaw=clean(block.match(/Dept\.-Class\s+([0-9-]+)/i)?.[1])||null; const vendorStyleRaw=clean(block.match(/Vendor Style:\s*([A-Z0-9./-]+)/i)?.[1])||null; const costRaw=normalizeMoney(block.match(/Cost\/Unit\s+\$?\s*([\d,.]+)/i)?.[1]); const descriptionRaw=parseDescription(blockLines); const colorRaw=clean(block.match(/COLOR:\s*(.+?)\s+Size\s+/i)?.[1])||null; const sizeRaw=clean(block.match(/\bSize\s+([A-Z0-9./-]+)\s+Qty\./i)?.[1])||null; const qtyRaw=normalizeInteger(block.match(/\bSize\s+[A-Z0-9./-]+\s+Qty\.\s+([\d,]+)/i)?.[1]); const qtyExtMatch=block.match(/\bQty\.\s+([\d,]+)\s+([\d,]+)\s+\$([\d,]+\.\d{2})/i); const extCostRaw=normalizeMoney(qtyExtMatch?.[3]);
    if(!vendorStyleRaw)continue; lines.push({ line_no:lines.length+1, customer_sku:customerSkuRaw, ticket_sku:null, upc:null, style_raw:vendorStyleRaw, style_code:null, color_raw:colorRaw, color_code:null, size_raw:sizeRaw, size_code:null, description:descriptionRaw, sales_price:costRaw, list_price:null, qty_total:qtyRaw, warehouse_code:null, raw:{ source:'zumiez_purchase_order_v1', zumiez_item_number_raw:customerSkuRaw, vendor_style_raw:vendorStyleRaw, style_resolution_hint:'EXACT_MASTER_SKU_NORMALIZED', dept_class_raw:deptClassRaw, description_raw:descriptionRaw, color_raw:colorRaw, size_raw:sizeRaw, quantity_raw:qtyRaw, quantity_semantics:'EACH', quantity_uom_raw:'QTY_UNITS_BY_COST_PER_UNIT', cost_per_unit_raw:costRaw, ext_cost_raw:extCostRaw } });
  }
  const printedSubtotal=normalizeInteger(oneLine.match(/\bSubtotal\s+([\d,]+)\s+\$[\d,]+(?:\.\d{2})?/i)?.[1]); const printedTotalAmount=normalizeMoney(oneLine.match(/\bTotal:\s*\$?\s*([\d,]+(?:\.\d{2})?)/i)?.[1]); const calculatedQty=lines.reduce((s,l)=>s+(Number(l.qty_total)||0),0)||null; const calculatedAmount=lines.reduce((s,l)=>s+(Number(l.raw?.ext_cost_raw)||0),0)||null; const conflicts=[];
  if(printedSubtotal!==null&&calculatedQty!==null&&printedSubtotal!==calculatedQty)conflicts.push({field:'totals.qty',code:'printed_total_mismatch',severity:'high',blocking:true,message:'Printed subtotal quantity does not match extracted line quantity sum.',printed:printedSubtotal,extracted:calculatedQty});
  if(printedTotalAmount!==null&&calculatedAmount!==null&&Math.abs(printedTotalAmount-calculatedAmount)>0.01)conflicts.push({field:'totals.amount',code:'printed_total_mismatch',severity:'high',blocking:true,message:'Printed total amount does not match extracted line extension sum.',printed:printedTotalAmount,extracted:calculatedAmount});
  return { parser:'zumiez', document_family:'zumiez_purchase_order', layout_version:'zumiez_purchase_order_v1', document_identity:{legal_entity_raw:clean(shipTo?.name_raw?.match(/ZUMIEZ INC/i)?.[0])||null,brand_raw:clean(oneLine.match(/\b(ZUMIEZ)\b/i)?.[1])||null,customer_candidate:'ZUMIEZ',customer_candidate_source:'document_family',a2000_customer_code:null}, confidence:orderNo&&lines.length?0.98:lines.length?0.82:0.4, header:{customer_raw:clean(shipTo?.name_raw)||null,customer_code:null,order_no:orderNo,order_date:normalizeDate(poDateRaw),start_date:normalizeDate(shipDateRaw),cancel_date:normalizeDate(cancelDateRaw),book_date:null,dept_raw:null,dept_code:null,division_code:null,store_raw:clean(shipTo?.store_code_raw)||null,store_code:null,terms_raw:termsRaw,terms_code:null,ship_via_code:null,warehouse_code:null,raw:{order_date_raw:poDateRaw,ship_date_raw:shipDateRaw,cancel_date_raw:cancelDateRaw,terms_raw:termsRaw,buyer_raw:buyerRaw,ship_to:shipTo}}, lines, totals:{qty:calculatedQty,amount:calculatedAmount,printed_qty_raw:printedSubtotal,printed_amount_raw:printedTotalAmount}, conflicts };
}
